on:
  push:
    tags:
    - "v*"

jobs:
  build-container-images:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: tag
      run: |
        echo "${${{ github.ref_name }}:1}" >> $GITHUB_OUTPUT

    - name: Install Forgejo CA
      run: |
        cat << EOF > /usr/local/share/ca-certificates/forgejo.crt
        ${{ github.FORGEJO_CRT }}
        EOF
        update-ca-certificates          

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: $${{ github.BUILDX_PLATFORMS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: $${{ github.BUILDX_PLATFORMS }}
        buildkitd-config-inline: |
          [registry."$${ github.FORGEJO_HOST }}"]
            ca=["/usr/local/share/ca-certificates/forgejo.crt"]

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Forgejo
      uses: docker/login-action@v3
      with:
        registry: $${ github.REGISTRY_HOST }}
        username: forgejo-runner
        password: ${{ secrets.FORGEJO_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: $${{ github.BUILDX_PLATFORMS }}
        tags: |
          funktionpi/oauth2-proxy:${{ steps.tag.outputs }}
          $${ github.REGISTRY_HOST }}/mirrors/oauth2-proxy:${{ steps.tag.outputs }}      
